language: ruby
script:
- bash ./scripts/deploy.sh
env:
  global:
    secure: gKw1cVYPsUYZYeSvP+oMttuMuUVEtI4SdCNBOGUrtG0u3PO2lfqG70E1H4waNo4pQ+VxokTRWh73m1wg8nPKHYZw2f3Tre3ql65hX+KyIr1mQt37Famys54aU+islyhDoXCyV1oHJeC1E+URly+KlymiFKvGfBzQQOJ8NgegJxPj0OfEgwyTi7q0LJO2tvnmPSQWMD8tYpncbsH6T+Dnd6nGp5e5sNi6IOAPARJEK2k2Rg1jqCduLYvmuSNQ8/PN8p8E/cXZ/TdMguBTXM2bEgVMPa+VQC5In5u0uTa/669zl+4khdcO31q572JifHDLHRrjz9JGtnRXlH8AqX1Z3ptQ6oJAUafYMgaA/qm6da6AdvzrIivCDmRwFnatHNXbgyq7MSj+BdPCgmxAGQIy+Q5QTCy/PuhiFWBYbdL8oouGrrOjozDilGpEFBYEqcUcHmubzCguE3bz6jH82+z+2RGL8SILwXUQTWnndO3TcjFdKlSwMb0F7zA+gcXIg2MfecLEwg9hGu0OaMvcrqwtA5pGtQOLlejx4/jg8lveXO+rLt4+VMEvIdGwUHd/iQ9sIudUABj/QXRSoj6khRqSOzFlKLuop0RdCgezPwAER1WmqYnTTMVS3tQNY9XCIONKpAgUhQsHp620H8/peROS2X+Ao7uT9L3S2qixUYvz6lA=
